[book]
authors = ["Start9"]
language = "en"
src = "src"
title = "StartOS"

[build]
build-dir = "../docs/start-os"

[preprocessor.tabs]

[output]

[output.html]
sidebar-header-nav = true
admonitions = true
no-section-label = false
default-theme = "ayu"
preferred-dark-theme = "ayu"
additional-css = ["./theme/docs-agent.css", "./theme/youtube.css", "./theme/tabs.css", "./accent.css"]
additional-js = ["./theme/docs-agent-init.js", "./theme/docs-agent.js", "./theme/youtube.js", "./theme/tabs.js", "./theme/home-link.js"]
git-repository-url = "https://github.com/start9labs/docs"
edit-url-template = "https://github.com/start9labs/docs/edit/master/start-os/{path}"
site-url = "/start-os/"

[output.html.fold]
enable = true
level = 0
